// Package replay provides the replay engine. It generates a Dockerfile and
// replay shell scripts from a capsule, then optionally executes them via
// docker or podman. The engine supports the modes from FR-011 (full-job,
// failed-step, test-only, dependency-install) and the network-deny mode
// from FR-019.
package replay

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/reproforge/reproforge/internal/capsule"
	"github.com/reproforge/reproforge/internal/logx"
)

// Mode constants.
const (
	ModeFullJob            = capsule.ReplayFullJob
	ModeFailedStep         = capsule.ReplayFailedStep
	ModeTestOnly           = capsule.ReplayTestOnly
	ModeDependencyInstall  = capsule.ReplayDependencyInstall
)

// Network constants.
const (
	NetworkAllow = "allow"
	NetworkDeny  = "deny"
)

// Options control a replay invocation.
type Options struct {
	Mode    string
	Network string
	// MemoryMB optionally caps container memory. 0 means default.
	MemoryMB int
	// CPUs optionally caps cpu cores. 0 means default.
	CPUs float64
	// TimeoutSec is the maximum wall-clock for the replay process.
	TimeoutSec int
	// EnvAllowlist is the set of env names that are passed through. Values
	// from caller env or .reproforge/local-secrets are included.
	EnvAllowlist []string
	// ExtraEnv are explicit KEY=VALUE pairs.
	ExtraEnv []string
	// Image overrides the auto-detected base image.
	Image string
	// Runtime is "docker" or "podman". Empty means auto-detect.
	Runtime string
	// DryRun prints the command without executing it.
	DryRun bool
	// WorkDir is the directory containing the unpacked capsule.
	WorkDir string
}

// Outcome records the result of a replay.
type Outcome struct {
	Mode       string
	Network    string
	ExitCode   int
	Reproduced bool
	Duration   time.Duration
	Image      string
	Reason     string
	Stdout     string
	Stderr     string
}

// Engine runs replays.
type Engine struct {
	Logger *logx.Logger
}

// NewEngine constructs an engine.
func NewEngine(l *logx.Logger) *Engine {
	if l == nil {
		l = logx.Default()
	}
	return &Engine{Logger: l}
}

// Generate writes the Dockerfile and replay.sh scripts under destDir/replay/.
// It does not require docker to be available.
func (e *Engine) Generate(c *capsule.Capsule, destDir string, opts Options) error {
	if c == nil {
		return errors.New("capsule is nil")
	}
	if destDir == "" {
		return errors.New("destDir empty")
	}
	if opts.Mode == "" {
		opts.Mode = ModeFailedStep
	}
	if opts.Network == "" {
		opts.Network = NetworkAllow
	}
	if err := os.MkdirAll(filepath.Join(destDir, "replay"), 0o755); err != nil {
		return err
	}
	image := opts.Image
	if image == "" {
		image = AutoImage(c.Runner)
	}

	dockerfile := generateDockerfile(c, image)
	if err := os.WriteFile(filepath.Join(destDir, "replay", "Dockerfile"), []byte(dockerfile), 0o644); err != nil {
		return err
	}

	replay := generateReplayScript(c, opts)
	if err := os.WriteFile(filepath.Join(destDir, "replay", "replay.sh"), []byte(replay), 0o755); err != nil {
		return err
	}

	failed := generateFailedStepScript(c)
	if err := os.WriteFile(filepath.Join(destDir, "replay", "failed-step.sh"), []byte(failed), 0o755); err != nil {
		return err
	}
	return nil
}

// AutoImage returns a sensible base image for a runner.
func AutoImage(r capsule.Runner) string {
	osLower := strings.ToLower(r.OS)
	switch {
	case strings.Contains(osLower, "ubuntu-24"):
		return "ubuntu:24.04"
	case strings.Contains(osLower, "ubuntu-22"):
		return "ubuntu:22.04"
	case strings.Contains(osLower, "ubuntu-20"):
		return "ubuntu:20.04"
	case strings.Contains(osLower, "ubuntu"), strings.Contains(osLower, "linux"):
		return "ubuntu:24.04"
	case strings.Contains(osLower, "debian"):
		return "debian:stable"
	case strings.Contains(osLower, "alpine"):
		return "alpine:3.20"
	case strings.Contains(osLower, "fedora"):
		return "fedora:40"
	default:
		return "ubuntu:24.04"
	}
}

func generateDockerfile(c *capsule.Capsule, baseImage string) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Auto-generated by reproforge. Repo %s, commit %s.\n", c.Repo, c.Commit)
	fmt.Fprintf(&sb, "FROM %s\n", baseImage)
	fmt.Fprintf(&sb, "ENV DEBIAN_FRONTEND=noninteractive\n")
	fmt.Fprintf(&sb, "RUN set -eux; apt-get update || true; apt-get install -y --no-install-recommends \\\n")
	fmt.Fprintf(&sb, "      ca-certificates curl git build-essential xz-utils tar unzip jq python3 python3-pip || true; \\\n")
	fmt.Fprintf(&sb, "    apt-get clean || true\n")
	fmt.Fprintf(&sb, "WORKDIR /work\n")
	fmt.Fprintf(&sb, "COPY ./source /work/source\n")
	fmt.Fprintf(&sb, "COPY ./replay /work/replay\n")
	fmt.Fprintf(&sb, "RUN chmod +x /work/replay/*.sh\n")
	fmt.Fprintf(&sb, "ENTRYPOINT [\"/work/replay/replay.sh\"]\n")
	return sb.String()
}

func generateReplayScript(c *capsule.Capsule, opts Options) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&sb, "# Auto-generated by reproforge — replay script for %s\n", c.Failure.Step)
	fmt.Fprintf(&sb, "set -euo pipefail\n")
	fmt.Fprintf(&sb, "MODE=\"${REPROFORGE_MODE:-%s}\"\n", opts.Mode)
	fmt.Fprintf(&sb, "echo \"reproforge: replay mode=$MODE step=%s\"\n", shellEscape(c.Failure.Step))
	fmt.Fprintf(&sb, "cd /work/source\n")
	fmt.Fprintf(&sb, "case \"$MODE\" in\n")
	fmt.Fprintf(&sb, "  full-job)\n")
	fmt.Fprintf(&sb, "    bash /work/replay/failed-step.sh\n")
	fmt.Fprintf(&sb, "    ;;\n")
	fmt.Fprintf(&sb, "  failed-step)\n")
	fmt.Fprintf(&sb, "    bash /work/replay/failed-step.sh\n")
	fmt.Fprintf(&sb, "    ;;\n")
	fmt.Fprintf(&sb, "  test-only)\n")
	if cmd := pickTestCommand(c); cmd != "" {
		fmt.Fprintf(&sb, "    %s\n", cmd)
	} else {
		fmt.Fprintf(&sb, "    bash /work/replay/failed-step.sh\n")
	}
	fmt.Fprintf(&sb, "    ;;\n")
	fmt.Fprintf(&sb, "  dependency-install)\n")
	for _, ic := range pickDepInstallCommands(c) {
		fmt.Fprintf(&sb, "    %s\n", ic)
	}
	fmt.Fprintf(&sb, "    ;;\n")
	fmt.Fprintf(&sb, "  *)\n")
	fmt.Fprintf(&sb, "    echo \"unknown mode: $MODE\" >&2; exit 64\n")
	fmt.Fprintf(&sb, "    ;;\n")
	fmt.Fprintf(&sb, "esac\n")
	return sb.String()
}

func generateFailedStepScript(c *capsule.Capsule) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&sb, "# Auto-generated by reproforge — failed step script\n")
	fmt.Fprintf(&sb, "set -euo pipefail\n")
	fmt.Fprintf(&sb, "echo \"reproforge: replaying failed step %s\"\n", shellEscape(c.Failure.Step))
	if c.Failure.Command != "" {
		fmt.Fprintf(&sb, "%s\n", c.Failure.Command)
	} else {
		fmt.Fprintf(&sb, "echo 'no failed command in capsule' >&2\n")
		fmt.Fprintf(&sb, "exit 1\n")
	}
	return sb.String()
}

func pickTestCommand(c *capsule.Capsule) string {
	cmd := strings.ToLower(c.Failure.Command)
	switch {
	case strings.Contains(cmd, "pytest"):
		if len(c.Failure.Tests) > 0 {
			return "pytest " + strings.Join(quoteAll(c.Failure.Tests), " ")
		}
		return "pytest -q"
	case strings.Contains(cmd, "go test"):
		if len(c.Failure.Tests) > 0 {
			pat := strings.Join(c.Failure.Tests, "|")
			return "go test ./... -run '" + pat + "'"
		}
		return "go test ./..."
	case strings.Contains(cmd, "mvn") || strings.Contains(cmd, "maven"):
		if len(c.Failure.Tests) > 0 {
			return "mvn -DskipITs=false -Dtest='" + strings.Join(c.Failure.Tests, ",") + "' test"
		}
		return "mvn -B test"
	case strings.Contains(cmd, "gradle"):
		if len(c.Failure.Tests) > 0 {
			arg := ""
			for _, t := range c.Failure.Tests {
				arg += " --tests '" + t + "'"
			}
			return "./gradlew test" + arg
		}
		return "./gradlew test"
	case strings.Contains(cmd, "npm"), strings.Contains(cmd, "pnpm"), strings.Contains(cmd, "yarn"), strings.Contains(cmd, "vitest"), strings.Contains(cmd, "jest"):
		return c.Failure.Command
	}
	return ""
}

func pickDepInstallCommands(c *capsule.Capsule) []string {
	cmd := strings.ToLower(c.Failure.Command)
	switch {
	case strings.Contains(cmd, "npm"):
		return []string{"npm ci || npm install"}
	case strings.Contains(cmd, "pnpm"):
		return []string{"pnpm install --frozen-lockfile || pnpm install"}
	case strings.Contains(cmd, "yarn"):
		return []string{"yarn install --frozen-lockfile || yarn install"}
	case strings.Contains(cmd, "pip"):
		return []string{"pip install -r requirements.txt"}
	case strings.Contains(cmd, "uv"):
		return []string{"uv pip install -r requirements.txt"}
	case strings.Contains(cmd, "go test"), strings.Contains(cmd, "go build"), strings.Contains(cmd, "go mod"):
		return []string{"go mod download"}
	case strings.Contains(cmd, "mvn"), strings.Contains(cmd, "maven"):
		return []string{"mvn -B -DskipTests dependency:resolve"}
	case strings.Contains(cmd, "gradle"):
		return []string{"./gradlew dependencies"}
	}
	return []string{"echo 'no dependency-install heuristic for this command'", "exit 0"}
}

func quoteAll(in []string) []string {
	out := make([]string, 0, len(in))
	for _, s := range in {
		out = append(out, shellEscape(s))
	}
	return out
}

func shellEscape(s string) string {
	if s == "" {
		return "''"
	}
	if !strings.ContainsAny(s, " \t'\"\\$&|;<>()`") {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

// Run executes the generated replay against the capsule. It is a no-op for
// DryRun mode.
func (e *Engine) Run(ctx context.Context, c *capsule.Capsule, capsuleDir, sourceDir string, opts Options) (Outcome, error) {
	if opts.Mode == "" {
		opts.Mode = ModeFailedStep
	}
	if opts.Network == "" {
		opts.Network = NetworkAllow
	}
	runtime := opts.Runtime
	if runtime == "" {
		runtime = detectRuntime()
	}
	if runtime == "" {
		return Outcome{Reason: "no container runtime found"}, errors.New("docker/podman not found in PATH")
	}
	image := opts.Image
	if image == "" {
		image = AutoImage(c.Runner)
	}

	tag := "reproforge-replay:" + shortFingerprint(c.Failure.Fingerprint)

	// Build context directory: capsuleDir/replay + sourceDir
	ctxDir, err := os.MkdirTemp("", "rf-build-*")
	if err != nil {
		return Outcome{}, err
	}
	defer os.RemoveAll(ctxDir)

	if err := os.MkdirAll(filepath.Join(ctxDir, "source"), 0o755); err != nil {
		return Outcome{}, err
	}
	if err := os.MkdirAll(filepath.Join(ctxDir, "replay"), 0o755); err != nil {
		return Outcome{}, err
	}
	if sourceDir != "" {
		if err := copyTree(sourceDir, filepath.Join(ctxDir, "source")); err != nil {
			return Outcome{}, fmt.Errorf("copy source: %w", err)
		}
	} else {
		// stub source directory so the COPY succeeds
		if err := os.WriteFile(filepath.Join(ctxDir, "source", ".keep"), []byte("no source available\n"), 0o644); err != nil {
			return Outcome{}, err
		}
	}
	if err := copyTree(filepath.Join(capsuleDir, "replay"), filepath.Join(ctxDir, "replay")); err != nil {
		return Outcome{}, fmt.Errorf("copy replay: %w", err)
	}

	if opts.DryRun {
		e.Logger.Info("dry-run replay", "image", image, "mode", opts.Mode, "network", opts.Network)
		return Outcome{Mode: opts.Mode, Network: opts.Network, Image: image, Reason: "dry-run"}, nil
	}

	// Build image
	buildCtx, cancel := withTimeout(ctx, opts.TimeoutSec)
	defer cancel()
	build := exec.CommandContext(buildCtx, runtime, "build", "-q", "-t", tag, "-f", filepath.Join(ctxDir, "replay", "Dockerfile"), ctxDir)
	build.Stdout = os.Stdout
	build.Stderr = os.Stderr
	if err := build.Run(); err != nil {
		return Outcome{Reason: fmt.Sprintf("docker build failed: %v", err), Image: image}, err
	}

	// Run image
	runArgs := []string{"run", "--rm"}
	if opts.Network == NetworkDeny {
		runArgs = append(runArgs, "--network", "none")
	}
	if opts.MemoryMB > 0 {
		runArgs = append(runArgs, "--memory", fmt.Sprintf("%dm", opts.MemoryMB))
	}
	if opts.CPUs > 0 {
		runArgs = append(runArgs, "--cpus", fmt.Sprintf("%g", opts.CPUs))
	}
	for _, k := range opts.EnvAllowlist {
		if v, ok := os.LookupEnv(k); ok {
			runArgs = append(runArgs, "-e", k+"="+v)
		}
	}
	for _, kv := range opts.ExtraEnv {
		runArgs = append(runArgs, "-e", kv)
	}
	runArgs = append(runArgs, "-e", "REPROFORGE_MODE="+opts.Mode)
	runArgs = append(runArgs, tag)

	runCtx, runCancel := withTimeout(ctx, opts.TimeoutSec)
	defer runCancel()
	cmd := exec.CommandContext(runCtx, runtime, runArgs...)
	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	start := time.Now()
	err = cmd.Run()
	dur := time.Since(start)

	o := Outcome{
		Mode: opts.Mode, Network: opts.Network,
		Image: image, Stdout: stdout.String(), Stderr: stderr.String(),
		Duration: dur,
	}
	if err == nil {
		o.ExitCode = 0
		o.Reproduced = c.Failure.ExitCode == 0
		o.Reason = "command succeeded"
		return o, nil
	}
	if exitErr, ok := err.(*exec.ExitError); ok {
		o.ExitCode = exitErr.ExitCode()
		o.Reproduced = c.Failure.ExitCode != 0 && o.ExitCode != 0
		o.Reason = fmt.Sprintf("replay exited with %d", o.ExitCode)
		return o, nil
	}
	o.Reason = err.Error()
	return o, err
}

// withTimeout wraps a context with the configured timeout. 0 means no timeout
// (we simply return the input context with a no-op cancel).
func withTimeout(parent context.Context, sec int) (context.Context, context.CancelFunc) {
	if sec <= 0 {
		return parent, func() {}
	}
	return context.WithTimeout(parent, time.Duration(sec)*time.Second)
}

func detectRuntime() string {
	for _, c := range []string{"docker", "podman"} {
		if _, err := exec.LookPath(c); err == nil {
			return c
		}
	}
	return ""
}

func shortFingerprint(fp string) string {
	fp = strings.TrimPrefix(fp, "sha256:")
	if len(fp) > 12 {
		fp = fp[:12]
	}
	if fp == "" {
		fp = "unknown"
	}
	return fp
}

// copyTree recursively copies src into dst.
func copyTree(src, dst string) error {
	return filepath.WalkDir(src, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		mode := os.FileMode(0o644)
		if info, err := os.Stat(p); err == nil {
			mode = info.Mode().Perm()
		}
		return os.WriteFile(target, b, mode)
	})
}
