package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/reproforge/reproforge/internal/capsule"
	"github.com/spf13/cobra"
)

// FR-033: emit a portable build script that reproduces the failing job
// without GitHub Actions. The output is intentionally simple — a Bash script
// that mirrors what the replay container would do, plus an optional Earthfile.
func newMigrateCmd() *cobra.Command {
	var (
		outDir string
		format string
	)
	cmd := &cobra.Command{
		Use:   "migrate <capsule>",
		Short: "Emit a portable shell script (and optional Earthfile) that reproduces the failing job outside GitHub Actions",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			_, c, err := loadCapsule(args[0])
			if err != nil {
				return err
			}
			if outDir == "" {
				outDir = "./reproforge-migration"
			}
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return err
			}
			switch format {
			case "shell":
				if err := writeShellMigration(outDir, c); err != nil {
					return err
				}
			case "earthly":
				if err := writeEarthfile(outDir, c); err != nil {
					return err
				}
			case "all":
				if err := writeShellMigration(outDir, c); err != nil {
					return err
				}
				if err := writeEarthfile(outDir, c); err != nil {
					return err
				}
			default:
				return fmt.Errorf("unknown format %q", format)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "wrote migration scripts to %s\n", outDir)
			return nil
		},
	}
	cmd.Flags().StringVar(&outDir, "out", "", "output directory")
	cmd.Flags().StringVar(&format, "format", "all", "shell | earthly | all")
	return cmd
}

func writeShellMigration(dir string, c *capsule.Capsule) error {
	var sb strings.Builder
	fmt.Fprintf(&sb, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&sb, "# Auto-generated by reproforge migrate.\n")
	fmt.Fprintf(&sb, "# Repo: %s, commit: %s, workflow: %s, job: %s\n",
		c.Repo, c.Commit, c.Workflow, c.Job)
	fmt.Fprintf(&sb, "set -euo pipefail\n\n")
	fmt.Fprintf(&sb, "REPRO_REPO=%q\n", c.Repo)
	fmt.Fprintf(&sb, "REPRO_COMMIT=%q\n", c.Commit)
	fmt.Fprintf(&sb, "WORKDIR=\"${WORKDIR:-/tmp/reproforge-migrate}\"\n")
	fmt.Fprintf(&sb, "mkdir -p \"$WORKDIR\" && cd \"$WORKDIR\"\n")
	fmt.Fprintf(&sb, "if [ ! -d repo ]; then\n  git clone https://github.com/$REPRO_REPO repo\nfi\n")
	fmt.Fprintf(&sb, "cd repo && git fetch origin && git checkout %q\n\n", c.Commit)
	fmt.Fprintf(&sb, "echo \"reproforge: replaying step '%s'\"\n", strings.ReplaceAll(c.Failure.Step, "\"", "\\\""))
	if c.Failure.Command != "" {
		fmt.Fprintf(&sb, "%s\n", c.Failure.Command)
	} else {
		fmt.Fprintf(&sb, "echo 'no failed command captured'\nexit 1\n")
	}
	if err := os.WriteFile(filepath.Join(dir, "migrate.sh"), []byte(sb.String()), 0o755); err != nil {
		return err
	}
	return nil
}

func writeEarthfile(dir string, c *capsule.Capsule) error {
	var sb strings.Builder
	fmt.Fprintf(&sb, "VERSION 0.7\n")
	fmt.Fprintf(&sb, "# Auto-generated by reproforge migrate.\n\n")
	fmt.Fprintf(&sb, "FROM %s\n", earthlyBaseImage(c.Runner.OS))
	fmt.Fprintf(&sb, "WORKDIR /work\n\n")
	fmt.Fprintf(&sb, "build:\n")
	fmt.Fprintf(&sb, "    GIT CLONE https://github.com/%s repo\n", c.Repo)
	fmt.Fprintf(&sb, "    RUN cd repo && git checkout %s\n", c.Commit)
	if c.Failure.Command != "" {
		fmt.Fprintf(&sb, "    RUN cd repo && %s\n", c.Failure.Command)
	} else {
		fmt.Fprintf(&sb, "    # no failed command captured; supply one below\n")
		fmt.Fprintf(&sb, "    RUN cd repo && echo 'edit me'\n")
	}
	return os.WriteFile(filepath.Join(dir, "Earthfile"), []byte(sb.String()), 0o644)
}

func earthlyBaseImage(osHint string) string {
	osHint = strings.ToLower(osHint)
	switch {
	case strings.Contains(osHint, "ubuntu-24"):
		return "ubuntu:24.04"
	case strings.Contains(osHint, "ubuntu-22"):
		return "ubuntu:22.04"
	}
	return "ubuntu:24.04"
}
